# Pittsburgh Bridges Data Set
### SVM Analysis: distinc SVM classifiers trained by means of Grid Search approach

- https://www.datacamp.com/community/tutorials/categorical-datas
- http://cmdlinetips.com/
- https://scikit-learn.org/stable/auto_examples/model_selection/plot_roc_crossval.html#sphx-glr-auto-examples-model-selection-plot-roc-crossval-py
- https://chrisalbon.com/
- https://www.datacamp.com/community/tutorials/svm-classification-scikit-learn-python

In [1]:
# === STANDARD IMPORTS ==== #
print(__doc__)

import pandas as pd
import numpy as np

%matplotlib inline
# Matplotlib pyplot provides plotting API
import matplotlib as mpl
from matplotlib import pyplot as plt
import chart_studio.plotly.plotly as py
import seaborn as sns

Automatically created module for IPython interactive environment

In [2]:
# === UTILS IMPORTS ==== #
from utils.display_utils import display_heatmap
from utils.display_utils import show_frequency_distribution_predictors
from utils.display_utils import show_categorical_predictor_values
from utils.display_utils import  show_cum_variance_vs_components

from utils.preprocessing_utils import preprocess_categorical_variables
from utils.preprocessing_utils import  preprocessing_data_rescaling

from utils.training_utils import svm_linear_classifier_grid_search
from utils.training_utils import plot_roc_crossval

In [3]:
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [4]:
# === READ INPUT DATASET ==== #
dataset_path = '/home/franec94/Documents/datasets/datasets_folders/pittsburgh-bridges-data-set'
dataset_name = 'bridges.data.csv'

# column_names = ['IDENTIF', 'RIVER', 'LOCATION', 'ERECTED', 'PURPOSE', 'LENGTH', 'LANES', 'CLEAR-G', 'T-OR-D', 'MATERIAL', 'SPAN', 'REL-L', 'TYPE']
column_names = ['RIVER', 'LOCATION', 'ERECTED', 'PURPOSE', 'LENGTH', 'LANES', 'CLEAR-G', 'T-OR-D', 'MATERIAL', 'SPAN', 'REL-L', 'TYPE']
dataset = pd.read_csv('{}/{}'.format(dataset_path, dataset_name), names=column_names, index_col=0)

In [5]:
# === SHOW SOME STANDARD DATASET INFOS ==== #
print('Dataset shape: {}'.format(dataset.shape))
print(dataset.info())

Dataset shape: (108, 12)
<class 'pandas.core.frame.DataFrame'>
Index: 108 entries, E1 to E109
Data columns (total 12 columns):
RIVER       108 non-null object
LOCATION    108 non-null object
ERECTED     108 non-null int64
PURPOSE     108 non-null object
LENGTH      108 non-null object
LANES       108 non-null object
CLEAR-G     108 non-null object
T-OR-D      108 non-null object
MATERIAL    108 non-null object
SPAN        108 non-null object
REL-L       108 non-null object
TYPE        108 non-null object
dtypes: int64(1), object(11)
memory usage: 11.0+ KB
None

In [6]:
# === SHOWING FIRSTS N-ROWS AS THEY ARE STORED WITHIN DATASET === #
dataset.head(5)

,RIVER,LOCATION,ERECTED,PURPOSE,LENGTH,LANES,CLEAR-G,T-OR-D,MATERIAL,SPAN,REL-L,TYPE
E1,M,3,1818,HIGHWAY,?,2,N,THROUGH,WOOD,SHORT,S,WOOD
E2,A,25,1819,HIGHWAY,1037,2,N,THROUGH,WOOD,SHORT,S,WOOD
E3,A,39,1829,AQUEDUCT,?,1,N,THROUGH,WOOD,?,S,WOOD
E5,A,29,1837,HIGHWAY,1000,2,N,THROUGH,WOOD,SHORT,S,WOOD
E6,M,23,1838,HIGHWAY,?,2,N,THROUGH,WOOD,?,S,WOOD

In [7]:
# === INVESTIGATING DATASET IN ORDER TO DETECT NULL VALUES === #
print('Before preprocessing dataset and handling null values')
result = dataset.isnull().values.any()
print('There are any null values ? Response: {}'.format(result))

result = dataset.isnull().sum()
print('Number of null values for each predictor:\n{}'.format(result))

Before preprocessing dataset and handling null values
There are any null values ? Response: False
Number of null values for each predictor:
RIVER       0
LOCATION    0
ERECTED     0
PURPOSE     0
LENGTH      0
LANES       0
CLEAR-G     0
T-OR-D      0
MATERIAL    0
SPAN        0
REL-L       0
TYPE        0
dtype: int64

In [8]:
# === DISCOVERING VALUES WITHIN EACH PREDICTOR DOMAIN === #
columns_2_avoid = ['ERECTED', 'LENGTH', 'LOCATION', 'LANES']
# columns_2_avoid = None
list_columns_2_fix = show_categorical_predictor_values(dataset, columns_2_avoid)

RIVER  :  ['A', 'M', 'O', 'Y']
PURPOSE  :  ['AQUEDUCT', 'HIGHWAY', 'RR', 'WALK']
CLEAR-G  :  ['?', 'G', 'N']
T-OR-D  :  ['?', 'DECK', 'THROUGH']
MATERIAL  :  ['?', 'IRON', 'STEEL', 'WOOD']
SPAN  :  ['?', 'LONG', 'MEDIUM', 'SHORT']
REL-L  :  ['?', 'F', 'S', 'S-F']
TYPE  :  ['?', 'ARCH', 'CANTILEV', 'CONT-T', 'NIL', 'SIMPLE-T', 'SUSPEN', 'WOOD']

In [9]:
# === FIXING, UPDATING NULL VALUES CODED AS '?' SYMBOL  === #
# === WITHIN EACH CATEGORICAL VARIABLE, IF DETECTED ANY === #
print('Before', dataset.shape)
for _, predictor in enumerate(list_columns_2_fix):
    dataset = dataset[dataset[predictor] != '?']
print('After', dataset.shape)

_ = show_categorical_predictor_values(dataset, columns_2_avoid)

Before (108, 12)
After (88, 12)
RIVER  :  ['A', 'M', 'O', 'Y']
PURPOSE  :  ['AQUEDUCT', 'HIGHWAY', 'RR']
CLEAR-G  :  ['G', 'N']
T-OR-D  :  ['DECK', 'THROUGH']
MATERIAL  :  ['IRON', 'STEEL', 'WOOD']
SPAN  :  ['LONG', 'MEDIUM', 'SHORT']
REL-L  :  ['F', 'S', 'S-F']
TYPE  :  ['ARCH', 'CANTILEV', 'CONT-T', 'SIMPLE-T', 'SUSPEN', 'WOOD']

In [10]:
# === INTERMEDIATE RESULT FOUNDED === #
preprocess_categorical_variables(dataset, columns_2_avoid)
print(dataset.info())

<class 'pandas.core.frame.DataFrame'>
Index: 88 entries, E1 to E90
Data columns (total 12 columns):
RIVER       88 non-null int64
LOCATION    88 non-null object
ERECTED     88 non-null int64
PURPOSE     88 non-null int64
LENGTH      88 non-null object
LANES       88 non-null object
CLEAR-G     88 non-null int64
T-OR-D      88 non-null int64
MATERIAL    88 non-null int64
SPAN        88 non-null int64
REL-L       88 non-null int64
TYPE        88 non-null int64
dtypes: int64(9), object(3)
memory usage: 8.9+ KB
None

In [11]:
# dataset.boxplot('RIVER','TYPE',rot = 30,figsize=(5,6))

In [12]:
dataset.head(5)

,RIVER,LOCATION,ERECTED,PURPOSE,LENGTH,LANES,CLEAR-G,T-OR-D,MATERIAL,SPAN,REL-L,TYPE
E1,2,3,1818,2,?,2,2,2,3,3,2,6
E2,1,25,1819,2,1037,2,2,2,3,3,2,6
E5,1,29,1837,2,1000,2,2,2,3,3,2,6
E7,1,27,1840,2,990,2,2,2,3,2,2,6
E8,1,28,1844,1,1000,1,2,2,1,3,2,5

In [13]:
# dataset[['LENGTH', 'SPAN', 'LANES']] = dataset[['LENGTH', 'SPAN', 'LANES']].replace(to_replace='?', value=None, method='bfill')
# print(dataset['SPAN'].value_counts())
# print(dataset['LENGTH'].value_counts())
# print(dataset['LANES'].value_counts())

print('Before', dataset.shape)
columns_2_map = ['ERECTED', 'LANES']
for _, predictor in enumerate(columns_2_map):
    dataset = dataset[dataset[predictor] != '?']
    dataset[predictor] = np.array(list(map(lambda x: int(x), dataset[predictor].values)))
print('After', dataset.shape)
print(dataset.info())
print(dataset.head(5))

Before (88, 12)
After (80, 12)
<class 'pandas.core.frame.DataFrame'>
Index: 80 entries, E1 to E90
Data columns (total 12 columns):
RIVER       80 non-null int64
LOCATION    80 non-null object
ERECTED     80 non-null int64
PURPOSE     80 non-null int64
LENGTH      80 non-null object
LANES       80 non-null int64
CLEAR-G     80 non-null int64
T-OR-D      80 non-null int64
MATERIAL    80 non-null int64
SPAN        80 non-null int64
REL-L       80 non-null int64
TYPE        80 non-null int64
dtypes: int64(10), object(2)
memory usage: 8.1+ KB
None
    RIVER LOCATION  ERECTED  PURPOSE LENGTH  LANES  CLEAR-G  T-OR-D  MATERIAL  \
E1      2        3     1818        2      ?      2        2       2         3
E2      1       25     1819        2   1037      2        2       2         3
E5      1       29     1837        2   1000      2        2       2         3
E7      1       27     1840        2    990      2        2       2         3
E8      1       28     1844        1   1000      1        2       2         1

    SPAN  REL-L  TYPE
E1     3      2     6
E2     3      2     6
E5     3      2     6
E7     2      2     6
E8     3      2     5

/home/franec94/anaconda3/envs/data-space/lib/python3.7/site-packages/pandas/core/ops.py:1649: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

In [14]:
print('Before', dataset.shape)
columns_2_map = ['LOCATION', 'LANES', 'LENGTH']    
for _, predictor in enumerate(columns_2_map):
    dataset = dataset[dataset[predictor] != '?']
    dataset[predictor] = np.array(list(map(lambda x: float(x), dataset[predictor].values)))
print('After', dataset.shape)    
print(dataset.info())
print(dataset.head(5))

# columns_2_avoid = None
list_columns_2_fix = show_categorical_predictor_values(dataset, None)

Before (80, 12)
After (70, 12)
<class 'pandas.core.frame.DataFrame'>
Index: 70 entries, E2 to E90
Data columns (total 12 columns):
RIVER       70 non-null int64
LOCATION    70 non-null float64
ERECTED     70 non-null int64
PURPOSE     70 non-null int64
LENGTH      70 non-null float64
LANES       70 non-null float64
CLEAR-G     70 non-null int64
T-OR-D      70 non-null int64
MATERIAL    70 non-null int64
SPAN        70 non-null int64
REL-L       70 non-null int64
TYPE        70 non-null int64
dtypes: float64(3), int64(9)
memory usage: 7.1+ KB
None
    RIVER  LOCATION  ERECTED  PURPOSE  LENGTH  LANES  CLEAR-G  T-OR-D  \
E2      1      25.0     1819        2  1037.0    2.0        2       2
E5      1      29.0     1837        2  1000.0    2.0        2       2
E7      1      27.0     1840        2   990.0    2.0        2       2
E8      1      28.0     1844        1  1000.0    1.0        2       2
E9      2       3.0     1846        2  1500.0    2.0        2       2

    MATERIAL  SPAN  REL-L  TYPE
E2         3     3      2     6
E5         3     3      2     6
E7         3     2      2     6
E8         1     3      2     5
E9         1     3      2     5
RIVER  :  [1, 2, 3]
LOCATION  :  [1.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 11.0, 12.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 38.5, 39.5, 39.7, 40.0, 41.0, 42.0, 43.0, 44.0, 46.0, 47.0, 48.0, 49.0]
ERECTED  :  [1819, 1837, 1840, 1844, 1846, 1851, 1856, 1859, 1864, 1866, 1870, 1876, 1883, 1884, 1887, 1888, 1890, 1891, 1892, 1895, 1896, 1897, 1898, 1900, 1902, 1903, 1904, 1909, 1910, 1911, 1915, 1918, 1920, 1923, 1924, 1926, 1927, 1928, 1931, 1937, 1939, 1945, 1950, 1951, 1955, 1959, 1961, 1962, 1969, 1975, 1978]
PURPOSE  :  [1, 2, 3]
LENGTH  :  [840.0, 860.0, 870.0, 884.0, 885.0, 900.0, 950.0, 965.0, 980.0, 990.0, 1000.0, 1030.0, 1031.0, 1037.0, 1040.0, 1060.0, 1092.0, 1150.0, 1161.0, 1200.0, 1300.0, 1320.0, 1330.0, 1350.0, 1365.0, 1417.0, 1450.0, 1500.0, 1620.0, 1652.0, 1690.0, 1700.0, 1710.0, 1730.0, 1770.0, 1800.0, 1850.0, 2000.0, 2122.0, 2160.0, 2213.0, 2220.0, 2250.0, 2300.0, 2365.0, 2367.0, 2423.0, 2663.0, 2678.0, 2822.0, 3000.0, 3756.0, 4000.0, 4558.0]
LANES  :  [1.0, 2.0, 4.0, 6.0]
CLEAR-G  :  [1, 2]
T-OR-D  :  [1, 2]
MATERIAL  :  [1, 2, 3]
SPAN  :  [1, 2, 3]
REL-L  :  [1, 2, 3]
TYPE  :  [1, 2, 3, 4, 5, 6]

In [15]:
result = dataset.isnull().values.any()
# print('After handling null values\nThere are any null values ? Response: {}'.format(result))

result = dataset.isnull().sum()
# print('Number of null values for each predictor:\n{}'.format(result))

In [16]:
dataset.head(5)

,RIVER,LOCATION,ERECTED,PURPOSE,LENGTH,LANES,CLEAR-G,T-OR-D,MATERIAL,SPAN,REL-L,TYPE
E2,1,25.0,1819,2,1037.0,2.0,2,2,3,3,2,6
E5,1,29.0,1837,2,1000.0,2.0,2,2,3,3,2,6
E7,1,27.0,1840,2,990.0,2.0,2,2,3,2,2,6
E8,1,28.0,1844,1,1000.0,1.0,2,2,1,3,2,5
E9,2,3.0,1846,2,1500.0,2.0,2,2,1,3,2,5

In [17]:
dataset.describe(include='all')

,RIVER,LOCATION,ERECTED,PURPOSE,LENGTH,LANES,CLEAR-G,T-OR-D,MATERIAL,SPAN,REL-L,TYPE
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,1.642857,25.438571,1911.542857,2.214286,1597.657143,2.857143,1.257143,1.814286,2.071429,1.742857,1.728571,3.457143
std,0.723031,13.223347,36.010339,0.478308,780.237680,1.242785,0.440215,0.391684,0.428054,0.629831,0.797122,1.575958
min,1.000000,1.000000,1819.000000,1.000000,840.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.000000,15.250000,1891.250000,2.000000,1000.000000,2.000000,1.000000,2.000000,2.000000,1.000000,1.000000,2.000000
50%,1.500000,27.000000,1915.000000,2.000000,1325.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,4.000000
75%,2.000000,35.750000,1935.500000,2.000000,2000.000000,4.000000,1.750000,2.000000,2.000000,2.000000,2.000000,4.000000
max,3.000000,49.000000,1978.000000,3.000000,4558.000000,6.000000,2.000000,2.000000,3.000000,3.000000,3.000000,6.000000

In [18]:
columns_2_avoid = ['ERECTED', 'LENGTH', 'LOCATION']
# show_frequency_distribution_predictors(dataset, columns_2_avoid)

In [19]:
# corr_result = dataset.corr()
# display_heatmap(corr_result)

In [20]:
columns = dataset.columns
target_col = 'T-OR-D'

y = np.array(list(map(lambda x: 0 if x == 1 else 1, dataset[target_col].values)))
print(dataset['T-OR-D'].value_counts())
X = dataset.loc[:, dataset.columns != target_col]

2    57
1    13
Name: T-OR-D, dtype: int64

In [21]:
# Standardizing the features
scaler_methods = ['minmax', 'standard', 'norm']
scaler_method = 'standard'
rescaledX = preprocessing_data_rescaling(scaler_method, X)

shape features matrix X, after normalizing:  (70, 11)

In [22]:
n_components = rescaledX.shape[1]
pca = PCA(n_components=n_components)
# pca = PCA(n_components=2)

#X_pca = pca.fit_transform(X)
pca = pca.fit(rescaledX)
X_pca = pca.transform(rescaledX)
    
# fig = show_cum_variance_vs_components(pca, n_components)

# py.sign_in('franec94', 'QbLNKpC0EZB0kol0aL2Z')
# py.iplot(fig, filename='selecting-principal-components {}'.format(scaler_method))

In [23]:
principal_components = [pc for pc in '2,5,6,7,8,9,10'.split(',')]
for _, pc in enumerate(principal_components):
    n_components = int(pc)
    
    cum_var_exp_up_to_n_pcs = np.cumsum(pca.explained_variance_ratio_)[n_components-1]
    print(f"Cumulative varation explained up to {n_components} pcs = {cum_var_exp_up_to_n_pcs}")

Cumulative varation explained up to 2 pcs = 0.4773834215633187
Cumulative varation explained up to 5 pcs = 0.7585646019420444
Cumulative varation explained up to 6 pcs = 0.8261576843657991
Cumulative varation explained up to 7 pcs = 0.884139028528102
Cumulative varation explained up to 8 pcs = 0.9266193769276869
Cumulative varation explained up to 9 pcs = 0.9597684131004697
Cumulative varation explained up to 10 pcs = 0.984328073066738

In [24]:
# svm_linear_classifier_grid_search(rescaledX, y)

In [25]:
kernel_type = 'svm-rbf-kernel'
svm_linear_classifier_grid_search(rescaledX, y, kernel_type)

==== GRID SEARCH METHOD APPLYED ON: RBF_SVM_Classifier Technique ====
==== PREPROCESSING METHOD: MinMax Technique ====

********************
Grid Search attempt no. : 1
--- Classification Report ---

ValueError: Classification metrics can't handle a mix of binary and continuous targets